/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const deviceId: msRest.OperationURLParameter = {
  parameterPath: "deviceId",
  mapper: {
    required: true,
    serializedName: "deviceId",
    type: {
      name: "String"
    }
  }
};
